#!/bin/sh
set -e

# nginx configuration
#- $BACKEND_SERVICE
#- $WORKER_PROCESSES
#- $WORKER_CONNECTIONS
#- $CLIENT_BODY_BUFFER_SIZE
#- $CLIENT_HEADER_BUFFER_SIZE
#- $CLIENT_MAX_BODY_SIZE
#- $LARGE_CLIENT_HEADER_BUFFERS
#- $CLIENT_BODY_TIMEOUT
#- $CLIENT_HEADER_TIMEOUT
#- $KEEPALIVE_TIMEOUT
#- $SEND_TIMEOUT

envsubst '\$BACKEND_SERVICE,\$WORKER_PROCESSES, \$WORKER_CONNECTIONS, \$CLIENT_BODY_BUFFER_SIZE, \$CLIENT_HEADER_BUFFER_SIZE, \$CLIENT_MAX_BODY_SIZE, \$LARGE_CLIENT_HEADER_BUFFERS, \$CLIENT_BODY_TIMEOUT, \$CLIENT_HEADER_TIMEOUT, \$KEEPALIVE_TIMEOUT, \$SEND_TIMEOUT' < /opt/app-root/src/nginx/nginx.conf.template > "${NGINX_CONF_PATH}"
exec /usr/libexec/s2i/run
